import type { Metadata } from "next"
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css"

import Header from "@/components/layouts/Header"
import Sidebar from "@/components/layouts/Sidebar"

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      className="relative h-full w-full overflow-auto text-base"
      lang="zh-Hans"
      data-theme="light"
    >
      <body
        className="relative h-full w-full overflow-auto antialiased"
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />

        <aside className="absolute top-12.5 bottom-0 left-0 w-80">
          <Sidebar />
        </aside>

        <main className="absolute top-12.5 right-0 bottom-0 left-80 overflow-auto bg-neutral-200 p-2.5">
          {children}
          {/*  */}
        </main>
      </body>
    </html>
  )
}
